language: node_js
node_js:
- 7.5.0
install:
- npm install
script: npm test
deploy:
  provider: heroku
  api_key:
    secure: Kq04lZ6hT4l6Og/sN6bwz4s1PBIE0fsZcDvS4qi+aVYCZqRS1PVMaCSyi9yc2G7JvjH4bq0gZEpGN3SF3V3JchtLOJ6kDBPwc/iso+AO1thFyzGT2jdgz1K0lT57EgB6lvprv1/4Y5iXMN8+K21q19Ey85E6uaLlA2aFBgl9h59M+GwrFuzOq8KQFLBiaiY5LIfJQACtlAGEFDzEz7bCJzP61EzVNh6rITx6QeXRoCbt2LJ7aKX2Ujmr6gZCQrjfAelTX08Hm5SKZ27lLcm/82UhboJt9oMj7xB/mM8lSTYdw+9QsWH+dGxIp8xlh+KDSAHJYkr1ZfrcwqzGxXLTZrgOXQkaEI2mNShEr+TGO27i0AbbXN0nR4fbvzeoOK250bxAn/7+c/JZxLDvSw37jRzXiIvMNllZA2MgTEmS+TJ2Y64RLX1bceOJd4xPu2KyFKMRjUyCNkGroJuqj/cLnTrhqlSVTlBgE9uZoo6gWxwGs+SN+yFFWo9oy06azqWLl8reXih5MlLqnpEMx4WtD+aQlEmWsexySR8qTREjXPtWn1Q69wLj7S2fjQg1CuYVzyom8GTfFolgQUVPOpSN+LWvxi7zSeCqRcjkPh2IaG+5irAZIz8hh2F0YGMK2ybieKQzgpwoxG9GkmkqLihDgS3Qig26A8DaJ4WLTk11iLA=
  app: whiterain
  on:
    repo: sappy5678/WhiteRain
    branch: version1
